# coding: utf-8

"""
    sle-management-client

    Python SLE Provider Management Client

    OpenAPI spec version: 0.1.0
    Contact: oss@visionspace.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.cortex_config_api import CortexConfigApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCortexConfigApi(unittest.TestCase):
    """CortexConfigApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.cortex_config_api.CortexConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cortex_config_table(self):
        """Test case for get_cortex_config_table

        Returns the parameter names of a Cortex configuration table  # noqa: E501
        """
        pass

    def test_get_cortex_config_table_list(self):
        """Test case for get_cortex_config_table_list

        Get a list of the available configuration tables  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
