# coding: utf-8

"""
    sle-management-client

    Python SLE Provider Management Client

    OpenAPI spec version: 0.1.0
    Contact: oss@visionspace.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.cortex_command_api import CortexCommandApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCortexCommandApi(unittest.TestCase):
    """CortexCommandApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.cortex_command_api.CortexCommandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cortex_command_list(self):
        """Test case for get_cortex_command_list

        Returns a list of the availiable Cortex commands  # noqa: E501
        """
        pass

    def test_post_cortex_command(self):
        """Test case for post_cortex_command

        Send a command to the Cortex  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
