# coding: utf-8

"""
    sle-management-client

    Python SLE Provider Management Client

    OpenAPI spec version: 0.1.0
    Contact: oss@visionspace.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.service_instance import ServiceInstance  # noqa: E501
from openapi_client.rest import ApiException


class TestServiceInstance(unittest.TestCase):
    """ServiceInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceInstance(self):
        """Test ServiceInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.service_instance.ServiceInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
