# coding: utf-8

"""
    sle-management-client

    Python SLE Provider Management Client

    OpenAPI spec version: 0.1.0
    Contact: oss@visionspace.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.sle_config_api import SleConfigApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSleConfigApi(unittest.TestCase):
    """SleConfigApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.sle_config_api.SleConfigApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sle_config(self):
        """Test case for get_sle_config

        Returns the current value of a SLE configuration parameter  # noqa: E501
        """
        pass

    def test_get_sle_config_list(self):
        """Test case for get_sle_config_list

        Get a list of the available configuration parameters  # noqa: E501
        """
        pass

    def test_patch_sle_config(self):
        """Test case for patch_sle_config

        Update a SLE configuration parameter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
