# coding: utf-8

"""
    sle-management-client

    Python SLE Provider Management Client

    OpenAPI spec version: 0.1.0
    Contact: oss@visionspace.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (
    ApiTypeError,
    ApiValueError
)


class ServiceInstancesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_si(self, si, **kwargs):  # noqa: E501
        """Deletes a service instance by name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_si(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_si_with_http_info(si, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_si_with_http_info(si, **kwargs)  # noqa: E501
            return data

    def delete_si_with_http_info(self, si, **kwargs):  # noqa: E501
        """Deletes a service instance by name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_si_with_http_info(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['si']  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_si" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'si' is set
        if ('si' not in local_var_params or
                local_var_params['si'] is None):
            raise ApiValueError("Missing the required parameter `si` when calling `delete_si`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'si' in local_var_params:
            path_params['si'] = local_var_params['si']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances/{si}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_si_list(self, **kwargs):  # noqa: E501
        """Deletes all loaded service instances  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_si_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_si_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.delete_si_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def delete_si_list_with_http_info(self, **kwargs):  # noqa: E501
        """Deletes all loaded service instances  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_si_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_si_list" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_si(self, si, **kwargs):  # noqa: E501
        """Find service instance by name  # noqa: E501

        Returns a single service instance  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_si(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance identifier (required)
        :return: ServiceInstance
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_si_with_http_info(si, **kwargs)  # noqa: E501
        else:
            (data) = self.get_si_with_http_info(si, **kwargs)  # noqa: E501
            return data

    def get_si_with_http_info(self, si, **kwargs):  # noqa: E501
        """Find service instance by name  # noqa: E501

        Returns a single service instance  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_si_with_http_info(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance identifier (required)
        :return: ServiceInstance
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['si']  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_si" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'si' is set
        if ('si' not in local_var_params or
                local_var_params['si'] is None):
            raise ApiValueError("Missing the required parameter `si` when calling `get_si`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'si' in local_var_params:
            path_params['si'] = local_var_params['si']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances/{si}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ServiceInstance',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_si_list(self, **kwargs):  # noqa: E501
        """Get a list of the loaded service instances  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_si_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_si_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_si_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_si_list_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of the loaded service instances  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_si_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_si_list" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patch_si(self, si, **kwargs):  # noqa: E501
        """Updates one or more service instance parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_si(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance that needs to be updated (required)
        :param dict(str, SleConfigParamsValues) request_body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patch_si_with_http_info(si, **kwargs)  # noqa: E501
        else:
            (data) = self.patch_si_with_http_info(si, **kwargs)  # noqa: E501
            return data

    def patch_si_with_http_info(self, si, **kwargs):  # noqa: E501
        """Updates one or more service instance parameters  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_si_with_http_info(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: Service instance that needs to be updated (required)
        :param dict(str, SleConfigParamsValues) request_body:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['si', 'request_body']  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_si" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'si' is set
        if ('si' not in local_var_params or
                local_var_params['si'] is None):
            raise ApiValueError("Missing the required parameter `si` when calling `patch_si`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'si' in local_var_params:
            path_params['si'] = local_var_params['si']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'request_body' in local_var_params:
            body_params = local_var_params['request_body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances/{si}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_si(self, si, **kwargs):  # noqa: E501
        """Adds a service instance  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_si(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: New service instance identifier (required)
        :param ServiceInstance service_instance:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_si_with_http_info(si, **kwargs)  # noqa: E501
        else:
            (data) = self.post_si_with_http_info(si, **kwargs)  # noqa: E501
            return data

    def post_si_with_http_info(self, si, **kwargs):  # noqa: E501
        """Adds a service instance  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_si_with_http_info(si, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str si: New service instance identifier (required)
        :param ServiceInstance service_instance:
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['si', 'service_instance']  # noqa: E501
        all_params.append('authentication')
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_si" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'si' is set
        if ('si' not in local_var_params or
                local_var_params['si'] is None):
            raise ApiValueError("Missing the required parameter `si` when calling `post_si`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'si' in local_var_params:
            path_params['si'] = local_var_params['si']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'service_instance' in local_var_params:
            body_params = local_var_params['service_instance']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        if 'authentication' in local_var_params:
            auth_settings = [local_var_params['authentication']]
        else:
            auth_settings = []

        return self.api_client.call_api(
            '/service-instances/{si}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
